on:
  push:
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_region: ${{ vars.AWS_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - run: |
          ls
          echo "Hola mundo"
      - name: Terraform Init
        run: |
          terraform init
          terraform fmt
          terraform validate
      - name: Terraform Plan
        run: terraform plan -out=plan.out
      - name: Terraform Apply
        run: terraform apply plan.out
